apiVersion: 1

datasources:
  - name: Elastic
    type: elasticsearch
    database: '[*]YYYY.MM.DD'
    url: '$ELASTIC_SERVER_URL'
    
    isDefault: true
    editable: false

    basicAuth: true
    basicAuthUser: '$ELASTIC_BASIC_USER'
    
    jsonData:
      esVersion: 8.0.0

      interval: Daily
      timeField: 'datetime_iso8601_with_timezone_offset'

      tlsAuth: true
      tlsAuthWithCACert: true

      serverName: '$ELASTIC_SERVER'
    
    secureJsonData:
      
      tlsCACert: $__file{/ca.crt}
      tlsClientCert: $__file{/cert/centralized-log-grafana-oss.crt}
      tlsClientKey: $__file{/cert/centralized-log-grafana-oss.key}

      basicAuthPassword: '$ELASTIC_BASIC_PASS'